services:
  pocketbase:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
    container_name: rentmanplus
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      PORT: ${PORT:-3001}
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped

volumes:
  pb_data:
